# Generated by Django 2.0.2 on 2018-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=3)),
                ('place', models.CharField(max_length=1)),
            ],
        ),
    ]
