# Generated by Django 2.0.2 on 2018-03-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_menues'),
    ]

    operations = [
        migrations.AddField(
            model_name='menues',
            name='img',
            field=models.ImageField(default='', upload_to='MenuPicture/'),
        ),
    ]
