# Generated by Django 2.0.2 on 2018-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_menues_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menues',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menues',
            name='img',
        ),
        migrations.RemoveField(
            model_name='menues',
            name='place',
        ),
        migrations.AddField(
            model_name='menues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menues',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AddField(
            model_name='menues',
            name='isSell',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menues',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
