# Generated by Django 2.0.2 on 2018-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
