# Generated by Django 2.0.1 on 2018-03-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='user',
        ),
        migrations.DeleteModel(
            name='Informations',
        ),
    ]
