# Generated by Django 2.0.1 on 2018-03-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0012_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='at',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='fastfood',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='grill',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='japanese',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='juice',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='late',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='line',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='location',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='price',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='service',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='shabu',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='steak',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='thai',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='twitter',
        ),
    ]
