# Generated by Django 2.0.1 on 2018-03-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0017_auto_20180315_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='fastfood',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='grill',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='japanese',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='juice',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='shabu',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='steak',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='thai',
        ),
    ]
