# Generated by Django 2.0.1 on 2018-03-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0019_auto_20180315_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='menues',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.Store'),
        ),
    ]
