# Generated by Django 2.0.1 on 2018-03-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0020_menues_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebyuser',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storebyuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='StoreByUser',
        ),
    ]
