# Generated by Django 2.0.1 on 2018-03-20 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0024_nparray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nparray',
            name='q_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=8), size=8),
        ),
    ]
