# Generated by Django 2.0.1 on 2018-03-20 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0027_remove_nparray_q_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='nparray',
            name='q_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='nparray',
            name='r_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None), blank=True, null=True, size=None),
        ),
    ]
