# Generated by Django 2.0.1 on 2018-03-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0028_auto_20180320_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nparray',
            name='q_array',
        ),
        migrations.RemoveField(
            model_name='nparray',
            name='r_array',
        ),
    ]
