# Generated by Django 2.0.1 on 2018-03-21 07:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0033_auto_20180321_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nparray',
            name='r_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
