# Generated by Django 2.0.1 on 2018-03-21 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0038_auto_20180321_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='pieces',
            new_name='Q_array',
        ),
        migrations.AddField(
            model_name='board',
            name='R_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]], size=None),
        ),
    ]
