# Generated by Django 2.0.1 on 2018-03-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0040_auto_20180321_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nparray',
            name='user',
        ),
        migrations.DeleteModel(
            name='NPArray',
        ),
    ]
